---
apiVersion: v1
kind: Namespace
metadata:
  name: redis-bs
---
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redis
  namespace: redis-bs
spec:
  # bootstrapNode:
  #   host: 10.42.3.181
  sentinel:
    replicas: 3
  redis:
    customConfig:
    - "replica-priority 100"
    replicas: 3
